markdown: kramdown
####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed
plugins:
  - jekyll-sitemap

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME


